### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by shevegen** [zyxwvuts/irc#1]
I modified the below IRC conversation to focus on the relevant.

Bottom line: termbox is required but it seems to have to reside in /home/daniel

Perhaps it should also check for /usr/include ?

<shevy> gcc -Wall -Wextra -pedantic -I/home/daniel/src/termbox/src -I/home/daniel/src/nev/include -DGaptype="unsigned long" -I.   -c -o src/gap.o src/gap.c
<shevy> I can't compile 
<shevy> he has hardcoded paths
<phale> shevy: yeah 
<shevy> I have no /home/daniel here
<phale> open an issue and tell that to him
<shevy> ok

**Comment by zyxwvuts** [comment]
You will need to modify config.h and config.mk with a text editor to suit your preferences, then simply run "make".
